### ISSUE TITLE
No updater detected

### ISSUE THREAD

**Issue by jimmi-wipster** [CreativeDo/ZXPInstaller#19]
Dragging zxp on zxp installer shows this error. What does "No updater detected" mean?

![zxp-pic](https://cloud.githubusercontent.com/assets/16637951/14938706/7c74d1b6-0f80-11e6-857c-63d938bd4f78.GIF)

**Comment by cameronmcefee** [comment]
Heh, great question. I have no idea >.<. From my [googling](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=fwUpdaterActive%3A+no+updater+detected), it looks like it might be something OS X related. In the case of the installer, it's happening when the installer tries to run the embedded Adobe command line installer tool. Unfortunately, it's beyond my skill set to diagnose beyond that.

Given that it's the first time I've seen it reported, it's possible it's a fluke thing based on your system or your current OS session. It sounds obvious, but have you tried restarting your computer and then running again? Perhaps it could be that simple…

**Comment by jimmi-wipster** [comment]
We have managed to get around it as the person I was trying to help didn't have sync turned on in Creative cloud. I've have trouble with getting users over line with installing zxp's using the "zxp installer" who are Adobe Enterprise users and don't use Creative cloud, have you seen this? 

They are running CC 2015:

![zxp-install](https://cloud.githubusercontent.com/assets/16637951/14939367/a3c91652-0f97-11e6-87b5-686e0da4185b.GIF)

**Comment by cameronmcefee** [comment]
Unfortunately, the base component of the installer is an Adobe CLI that provides generally unhelpful errors, usually a step better than “uh oh” (my favorite is “I/O error”). I've seen the error in the screenshot, but the CLI doesn't provide any useful debug data that would help to shed light on what's actually the cause. I also know it's prone to false positives and bugs so each ticket is generally it's a game of guessing whether each error is an error or an erroneous error >.<

I've had luck in a few cases asking people to uninstall the Extension Manager from their machine, if they still have it installed. In some cases it causes conflicts for CC 2015 because the CLI and the Extension Manager appear to share some sort of path that tells it that old versions cause conflicts with CC 2015 details (which it doesn't support).

In your particular example though, it sounds like you've noticed a pattern? That's about the only time I've been able to successfully debug the Adobe component of things—when weird stuff happens reliably. How does Adobe Enterprise (I'm unfamiliar) factor into things? Is it a method of app installation as an alternative to the CC app? Are the apps that get flagged as not compatible apps that technically should be fine based on the extension manifest?

**Comment by jimmi-wipster** [comment]
Yeah we have been telling people to uninstall Extension Manager. All the enterprise users we have talked to, we have been their first addon. Adobe support gave them the ExManCmd script to install our addon which isn't very helpful, that's why we have been pushing them towards this (thank you for that :100:  )   I'm not sure where to go to from here, hopefully Adobe come to the party and sort out the issues.
