### ISSUE TITLE
ADOBE PHOTOSHOP 2015.5 - will the ZXPInstaller be updated?

### ISSUE THREAD

**Issue by FidJenn** [CreativeDo/ZXPInstaller#20]
Hi guys! 
Thank you so much for the app!
Will there be an updated version that we could expect with the paths for the latest Photoshop upgrade?

**Comment by cameronmcefee** [comment]
To my knowledge, the installation locations are the same as before (everything pulls from a `/CEP/` directory). As long as the manifest correctly specifies Photoshop 17 is included, things should work. I just tested it myself and it appears to have worked.

Please let us know if you run into a situation that can confirm otherwise.

**Comment by FidJenn** [comment]
Thanks so much Cameron, that helped!!!

**Comment by FidJenn** [comment]
Cameron, 

I'm so sorry, we have updated our installation files and they worked like a charm for me and our developer, but all of our users are reporting the "installation failed because the extension is not compatible with the installed applications." error. Would you happen to have any ideas as to what could be causing the same file to work fine for some and give that error for others?

**Comment by cameronmcefee** [comment]
My experience with Adobe things has lead me to always assume the most complicated, convoluted, or unclear possibility is usually the one that is true. My gut tells me what your users are reporting is unrelated, you're just hearing about it more because everyone is updating right now. I could be wrong, but here's why I think this:

The ZXPInstaller is built on top of an Adobe command line utility, so we're at the mercy of what it can do and what it tells us (the part we contribute here is essentially just a GUI for it). When things go wrong the CLI returns error codes that I've cross referenced with some Adobe error messages posted deep in unrelated reference docs that are, at best, vaguely almost helpful. This is one of those ones that seems clear but also isn't. I haven't tested this recently, but I seem to remember "not compatible with the installed applications" to mean something like "the extension needs Photoshop but Photoshop is not installed", rather than "the extension needs Photoshop 2014 but Photoshop 2015.5 is installed."

You could check this by making a build of your extension that sets a range that does not include your version. Perhaps limit it to CS5 if you don't have that installed. Then try the ZXPInstaller to see what error you get. If it's the same error, then *perhaps* it's related (I still think it isn't). If it's a different error, you can dig into troubleshooting with your user to try to figure out why there's a mismatch. It could be user error like they are trying to install a Photoshop extension into Photoshop Elements. It could be a literal error where they think they've got an app installed but they didn't actually install it. It could also be one of those head -> desk errors where the application is installed and there is no clear explanation for why the installer can't figure that out. Sometimes reinstalling the Adobe application and/or restarting can fix those. Given my aforementioned theory about choosing the most convoluted answer, that's usually what I assume and try to rule out all the reasonable things on the way to figuring it out.

**Comment by FidJenn** [comment]
Thanks so much Cameron! We'll try what you suggested tomorrow! 
I really appreciate your time and willingness to help, thank you!

**Comment by Jolg42** [comment]
Hi!
They updated the ExManCmd for this new release.
I think this update need to be in ZXPInstaller to bring compatibility with the new Adobe's releases.

https://github.com/Adobe-CEP/CEP-Resources/issues/60#issuecomment-227539582
> By the way, Photoshop and Illustrator are using CEP 7.0, and other apps are still using CEP 6.1. To install extensions with new apps, please download latest version of ExManCmd from https://www.adobeexchange.com/resources/28.

**Comment by cameronmcefee** [comment]
Thanks @Jolg42, it seems like you're right. I'll push a new release today if it's a simple as swapping things out.

**Comment by FidJenn** [comment]
Thanks @Jolg42  and @cameronmcefee!

We'll be keeping an eye out for the update, please comment here when it's out, @cameronmcefee. Thanks again!

**Comment by cameronmcefee** [comment]
Alright, I pushed 1.5.0: https://github.com/CreativeDo/ZXPInstaller/releases/tag/1.5.0

I'm still skeptical that these issues are directly related because, despite seeing an adobe employee saying the core library was updated, it doesn't appear to have been recently. However, it's a newer version than the one we have bundled here, so it's worth updating anyway. @FidJenn, give this new one a try with your users and let me know if it fixes things, keeping in mind that if I'm correct, it won't.

**Comment by FidJenn** [comment]
YES!!

**Comment by FidJenn** [comment]
@cameronmcefee it solved the problem for a couple of beta-testers of our updated extension! Thank you!!!!

**Comment by FidJenn** [comment]
@cameronmcefee quick question - is the download from the main page http://zxpinstaller.com/ the updated version now?

**Comment by cameronmcefee** [comment]
Awesome, I'm glad to hear it, and happy to be wrong in this case. Yes, the site version is up to date.

**Comment by FidJenn** [comment]
@cameronmcefee thank you so much!
