### ISSUE TITLE
virus found

### ISSUE THREAD

**Issue by shakilofbd** [CreativeDo/ZXPInstaller#25]
I published a video on YouTube https://youtu.be/XC7MzBz6Cus
one user told me he found virus on the software.
https://www.virustotal.com/en/file/922613dc075ee8e96867e5a8669c9dfd57b88a2f6cd591e02270f9c84a9f0a8f/analysis/1471198482/
pls see the YouTube video comments.
how to I give him the answer.
pls solved the problem.
I also write a blog post https://www.artpsd.com/adobe-extension-manager-alternative-for-adobe-cc-2015.html

**Comment by cameronmcefee** [comment]
Hi @shakilofbd,

This is likely a false positive. All of the code within ZXPInstaller is open source in this repo, and the included dependencies are from credible developers. VirusTotal is saying that 1 out of 52 virus scanners is detecting behavior which may appear to be similar to what a piece of malware might do. In my mind, this is equivalent to calling the police on a kid wearing a hoodie because one of your neighbors says that sometimes criminals wear hoodies.

If it were more than 1/52 or was was a credible report indicating actual evidence in the code here or in one of the dependences I'd be more concerned, but for now, I am not. Like I said, the code is open so the paranoid are welcome to do their own investigating.
