### ISSUE TITLE
Installation error 413

### ISSUE THREAD

**Issue by chichilina** [CreativeDo/ZXPInstaller#27]
Hello,
I got status error 413 when trying to install WebZap extension in photoshop 2015.5 with Windows 10.
I do not find anything about this error. What does it mean please?
Best regards

**Comment by cameronmcefee** [comment]
Hi @chichilina,

I'm sorry for the trouble. ZXPInstaller pulls its error codes from the Adobe tool it's built on top of. The ones that come back as numbers rather than clean messages are ones that Adobe hasn't documented publicly. Unfortunately, your error is one of them.

From looking at their [documented codes](https://helpx.adobe.com/extension-manager/using/extension-manager-error-code-reference.html), the -4xx errors seem to be based on compatibility (wrong extensions installed, wrong apps installed, conflicting versions, etc). While I can only speculate, it's possible the version of WebZap you have isn't compatible with your current setup. Please note that because it isn't clear what the error actually is, you may be able to troubleshoot it with the WebZap's developer. I suggest contacting them, letting them know what Adobe applications you have installed, what CC versions you are using, the version of WebZap you have, and anything else that may help them figure out what is going on. They may be able to catch something obvious (like your version might not work with the CC 2015.5 or something along those lines), or provide alternative installation instructions.

If you do discover the cause, I'd greatly appreciate if you report back here so I can update the error messages to include an explanation for future users that run into it.

**Comment by chichilina** [comment]
do not discover cause. Creator give me Manual installation files.
Thanks
