### ISSUE TITLE
Code Signing Certificate

### ISSUE THREAD

**Issue by SmilePix** [CreativeDo/ZXPInstaller#30]
This is not really and issue, but a question. But first thanks for ZXPInstaller. I am glad to see that it still works with the latest release of Photoshop.
I tried it yesterday with an expired Certificate and it installed the extension without any warnings. Does ZXPInstaller ignore the Certificate?

Thanks in advance - Sam

**Comment by cameronmcefee** [comment]
Hi @SmilePix,

Off the top of my head, I'm not sure. ZXPInstaller uses Adobe's command line tool, so whatever it does, ZXPInstaller will do. Without actually looking into it, here are a few possible scenarios:

- Assuming you've got your terminology correct, the certificate is used to sign the code when you publish and isn't applicable at runtime. As far as I know, you can't sign code with an expired certificate (said anecdotally, without much research), so I assume you signed the code while it was valid, but now the certificate has expired. If you signed it with a timestamp, the signature remains valid because the certificate was valid *at the time of signing* and thus so is the code. So in this scenario everything is actually fine.

- If you've got your terminology wrong and you mean you've got an invalid signature (code has been modified post-signing), I'm not sure how the command line tool will handle it, but the Adobe application will throw a "signature is invalid" error if you try to launch the extension.

- It's also possible that the command line tool is actually throwing an error that isn't getting caught, though I'd presume it'd be thrown in the same way as all the other errors, which should work.

If you're command line savvy and want to try it for yourself, you can find it here: https://www.adobeexchange.com/resources/28

If any of these answers happen to shed light on the topic, I'd to know what your resolution is.

**Comment by SmilePix** [comment]
Thanks for the clarification on Code Signing Certificate. I was thinking I would have to repackage my extension with a current certificate, but from you explanation, I see that once the extension has been packaged, installing the extension without a current certificate works fine.

Thanks again - Sam
----------
SmilePix
"Picturing the Perfect Smile"
http://www.smilepix.com
781-577-7700
