### ISSUE TITLE
“ZXPInstaller” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by janinepetzer** [CreativeDo/ZXPInstaller#44]
Whenever I try open ZXP Installer I get this popup: “ZXPInstaller” can’t be opened because it is from an unidentified developer. Please help with getting around this? Or do I need to download it from somewhere else?
![screen shot 2018-01-15 at 10 12 33 am](https://user-images.githubusercontent.com/33057418/34932377-43458c86-f9db-11e7-91e6-5310731a58d6.png)

**Comment by cameronmcefee** [comment]
Hi @janinepetzer,

Since ZXPInstaller is a small, open source project, we don't sign the extension with a certificate from a recognized certificate authority (they can be costly and require more centralized organization than this project currently has). The application is still safe and valid (the code is open source so you're able to verify it for yourself), but without the certificate, macOS will provide the warning you receive when you have the most restrictive settings set.

You can find instructions for adjusting those settings here: https://support.apple.com/en-us/HT202491. If you so choose, you do not need to disable them permanently, just for the duration of the installation.

**Comment by janinepetzer** [comment]
Brilliant @cameronmcefee . Thank you!
