### ISSUE TITLE
PSD Covers zxp won't install (Adobe CC) 2018 or most updated version

### ISSUE THREAD

**Issue by chrisduncandesign** [CreativeDo/ZXPInstaller#46]
<img width="242" alt="screen shot 2018-06-02 at 11 24 17 am" src="https://user-images.githubusercontent.com/4750209/40878479-87a18ffe-6657-11e8-9274-34034e72315a.png">

**Comment by cameronmcefee** [comment]
At what point does that error appear? That doesn't look like a message from ZXPInstaller.

**Comment by chrisduncandesign** [comment]
you are correct, that was from Anastasia's Extension Manager. Attached is the ZXPInstaller one. It forces me to log into Adbobe Extesion Manager twice and then I get the Error message. 

Thanks for your response ---  would love to hear what you think I should do!



<img width="1445" alt="screen shot 2018-06-02 at 5 28 54 pm" src="https://user-images.githubusercontent.com/4750209/40881382-e76d4e9a-668a-11e8-9b41-07c011d8d5c2.png">
<img width="753" alt="screen shot 2018-06-02 at 5 32 03 pm" src="https://user-images.githubusercontent.com/4750209/40881383-e7879df4-668a-11e8-9a41-e0b46181873c.png">

**Comment by cameronmcefee** [comment]
I don't know this for sure, but I suspect _Anastasia's Extension Manager_ uses the same underlying library that ZXPInstaller uses, ExManCmd, a command line utility published by Adobe. I base this on the fact that while the messages are slightly different, they're similar and the [error codes are the same](https://github.com/CreativeDo/ZXPInstaller/blob/bb2cb732abcecd9735d8ccf394bc4cd2f31c7de0/app/src/messages.js).

What this tells me (from a debugging mindset) is that since two separate applications are telling you similar things, this is not an issue that either extension manager can fix for you. I'm not familiar with the error code it is giving you or the scenario that it suggests. There are two things I'd try:

- If it is the result of a corrupt ZXP file, which is something the extension developer should be able to help you with, you can try downloading the file again, being sure not to use any download utilities that may have caused an issue. However, this typically produces a "invalid signature" error, so this may not be what is happening.

- The error messages, when considered together, don't give a clear indication of what is actually wrong. Most likely something is not as it should be with your computer which is causing an issue with the installation. This could be a false positive or it could be true, but in either case, Adobe does not provide a specific enough error message to trouble shoot. If it were me in this scenario, I'd uninstall Photoshop and the Creative Cloud app, restart my computer, and then reinstall them. This would rule out most "it got itself into a weird state" issues that can cause false positives.

Beyond that, I unfortunately don't have any better advice other than to contact Adobe. It's technically their tool (ExManCmd) that's throwing the error so they'd know best how to fix it.
