### ISSUE TITLE
Hybrid extension - just plugin is installed on Windows

### ISSUE THREAD

**Issue by StefanRiedmann** [CreativeDo/ZXPInstaller#48]
ZXPInstaller works perfectly fine with HTML-only extension. But now that I created a hybrid extension containing plugins, ZXP Installer on Windows only deploys the aip file, but not the HTML extension. No error is shown, but I can't find the extension in any of the supported extension folders.

**Comment by cameronmcefee** [comment]
Can you confirm the issue is specifically caused by ZXPInstaller? For example, if you install using [ExMan](https://technologypartners.adobe.com/home/support/exman-com-line-tool.html), can you install successfully? ZXPInstaller uses this to install and I don't see anything in the docs that would indicated the process is different for html vs hybrid in a way that we might be missing.

Since your other installation worked fine and you're not seeing errors, I suspect you might have a manifest configuration issue instead. However, if you can get it to work via another method that uses the manifest, then there might be an issue on our end.

**Comment by StefanRiedmann** [comment]
I didn't try ExMan yet, but with Anastasiy's tool it works
http://install.anastasiy.com/
And on Mac, it also works with ZXPInstaller, so it's just a Windows issue. 

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
     <macromedia-extension id="com.ciclosoftware.ygcontras" name="YG Contras (alpha)" requires-restart="true" version="0.120">
        <author name="Ciclo Software"/>
        <description><![CDATA[Managing labels]]></description>
        <license-agreement><![CDATA[Free for trials]]></license-agreement>
        <products>
           <product familyname="Illustrator" maxversion="" primary="true" version="22.0"/>
        </products>
        <files>
        
        <file destination="" 
                file-type="CSXS" 
                products="Illustrator,Illustrator32,Illustrator64" 
                maxVersion="22.9" minVersion="22.0"
                source="HTML/ygcontras_v0.120-alpha_ext.zxp"/> 
        
        
        <file   source="MAC/ScriptMessage.aip"
                destination="$plugin/ygcontras" 
                products="Illustrator" 
                maxVersion="22.9" minVersion="22.0"
                platform="mac"
                shared="true"/>
    
        
        <file   source="WIN_64/ScriptMessage.aip"
                destination="$plugin/ygcontras" 
                products="Illustrator64" 
                maxVersion="22.9" minVersion="22.0"
                platform="win"
                shared="true"/>
    
        
        <file   source="WIN_32/ScriptMessage.aip"
                destination="$plugin/ygcontras" 
                products="Illustrator32" 
                maxVersion="22.9" minVersion="22.0"
                platform="win"
                shared="true"/>
    </files>
</macromedia-extension>

**Comment by cameronmcefee** [comment]
Are you able to provide a file so I can test it out? If it's a paid extension, you may send it to me directly at mailbot@cameronmcefee.com. I'll remove it as soon as I've had a chance to test what you're describing.

**Comment by StefanRiedmann** [comment]
Can you believe it ... I prepared a test zxp for you, with changes in the manifests, and it works. So it's definitely a problem on my side - just weird that it only appears on Windows. 

I have another question. I tried to delete the extension manually of the system. I found the aip and also the extension folder itself and deleted it (it also disappeared from Illustrator). But zxpinstaller still says that there is a newer version already installed. What else do I have to cleanup? In the Adobe documentation I only find the folders where the extensions are installed.

**Comment by cameronmcefee** [comment]
> Can you believe it

This is the story of most bug reports I _begin_ to file. I've now developed a habit of writing a report, then testing once more before submitting. I almost always realize it was my own fault >.<

> zxpinstaller still says that there is a newer version already installed

That sort of check is done by ExMan which looks at some Adobe manifest (I don't know if anyone has figured out where it is) that records what is installed. Since you're deleting the files manually rather than uninstalling via ExMan, that manifest doesn't get updated to reflect that you've removed the extension. Since ZXPInstaller is install-only, there's not currently a clean way to uninstall extensions.

I believe all the maintainers have switched to making our own native installers for our extensions, so I don't anticipate this changing in the future. If you're hearty enough to want to add it yourself, PRs are welcome.

**Comment by StefanRiedmann** [comment]
Thank you for your explanations. I'm the only programmer in our project so far, and I can't invest time in an own installer. Anyway the idea is to deploy through Creative Cloud in the future, but I need a good installer for testing. I'll keep using zxpinstaller for sure, and will get into ExMan asap for uninstalling versions. 
Thank you very much!
Stefan
