### ISSUE TITLE
adobe zxp installer message: installation failed because the extension is not compatible 

### ISSUE THREAD

**Issue by OrsonB** [CreativeDo/ZXPInstaller#49]
I just installed the ZXP installer software, and when i try to install the extension it says:

"Installation failed because the extension is not compatible with the installed application"
![could not install](https://user-images.githubusercontent.com/42759897/44698947-3bef4c00-aa3f-11e8-9f6a-97a1b0e95439.JPG)

**Comment by cameronmcefee** [comment]
Hi @OrsonB,

Unless you have evidence that indicates otherwise, that message is telling you that you don't have an app installed that supports your extension. You should check with the extension creator to see what is up. It's likely you either misunderstand which versions are supported, or have an old version of an extension that has since been updated to support new CC versions.

**Comment by OrsonB** [comment]
Hi Cameron,

Thank you for responding back, ok, I will talk to the creator and see what
he states about it, thank you.
