### ISSUE TITLE
Installation failed because of a file operation error

### ISSUE THREAD

**Issue by bwolf33** [CreativeDo/ZXPInstaller#51]
I get this error when trying to install a ZXP file. What next?

**Comment by cameronmcefee** [comment]
This one, unfortunately, comes right from the Adobe installer ZXPInstaller uses and is the equivalent of ¯\_(ツ)_/¯. It means something went wrong while trying to read or write installation files, but beyond that, it's impossible to know. You can restart your computer and try again, which can sometimes fix fluke issues. Otherwise, you could try an alternative zxp intaller like https://github.com/nvkzNemo/UberManager which I believe does not use the same Adobe installer under the hood.
